version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: kitobium_postgres
    restart: always
    environment:
      POSTGRES_DB: kitobium_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: kitobium_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kitobium.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db